services:
  api:
    build: .
    ports:
      - "8000:5000"
    environment:
      - ENV=production
      - DATABASE_URI=mysql+pymysql://root:example@db:3306/melodyvault
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=melodyvault
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
